version: "3"
services:
    app_subsistema2:
        image: mguindel/aos_subsistema2:2.5
        container_name: server_subsistema2
        restart: always
        ports:
            - 8080:8080
        links:
            - mysql_subsistema2
    mysql_subsistema2:
        image: asdiaz/aos_bd:1.2
        container_name: db_subsistema2
        environment:
            MYSQL_DATABASE: practica_aos
            MYSQL_ROOT_PASSWORD: 1234
        ports:
            - "3306:3306"
