version: "3"
services:
    app:
        image: asdiaz/aos_subsistema2:2.4
        container_name: server
        restart: always
        ports:
            - 8080:8080
        links:
            - mysql
    mysql:
        image: asdiaz/aos_bd:1.2
        container_name: db
        environment:
            MYSQL_DATABASE: practica_aos
            MYSQL_ROOT_PASSWORD: 1234
        ports:
            - "3306:3306"
